# Generated by Django 4.1.7 on 2023-06-21 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
