# Generated by Django 4.2.10 on 2024-03-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_activitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="done",
        ),
        migrations.AddField(
            model_name="link",
            name="keyword",
            field=models.CharField(default="", max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="link",
            name="link",
            field=models.URLField(default="", max_length=2048, unique=True),
        ),
    ]
