# Generated by Django 4.1.7 on 2023-06-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_activitylog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="done",
        ),
        migrations.AddField(
            model_name="link",
            name="keyword",
            field=models.CharField(default="", max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="link",
            name="link",
            field=models.URLField(default="", max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
