# Generated by Django 4.2.10 on 2024-03-09 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_remove_link_done_link_keyword_link_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["keyword"]},
        ),
        migrations.AlterField(
            model_name="link",
            name="description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="keyword",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="link",
            name="link",
            field=models.URLField(default="", max_length=2048),
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=64, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="link",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.workspace",
            ),
        ),
    ]
